#!/usr/bin/env python3
"""
money_bleeds.py — the company-health exceptions report ("Money Bleeds").

Replaces the old KPI dashboard idea with a short list of things that are
provably wrong and cost money (the user 2026-07-16):

  1. DRAWS WITH NO INVOICE (MFD + CP only — RP never has a G702)
       MFD: active projects come from the 'WIP Master' tab; each project's
            DRAWS folder on the Multi Family volume is checked — LATEST
            numbered draw only ("we are already billing draws; this is for
            the future case — if the last draw has an invoice, move on").
       CP:  latest draw's G702 earned-less-retainage vs cumulative QBO
            invoiced for the project — a shortfall = a draw never invoiced.

  2. LIEN CLOCK on every open invoice (Texas Prop. Code Ch. 53)
       CP/MFD (commercial):  notice due the 15th of the 3rd month after the
                             WORK month.
       RP (residential):     15th of the 2nd month.
       Work month = INVOICE month (the user 2026-07-16: the RP invoice date
       is the last day on the job / finished 100%, and draws are billed in
       their work month — always run the clock from the invoice month).
       Deadlines roll BACKWARD off weekends (never forward). Retainage is a
       separate statutory track (completion-based, § 53.057) — retainage
       invoices are listed apart, not run through the monthly clock.
       Equipment-lease / note-payment invoices to subs are NOT construction
       income — excluded from the clock, listed on their own sheet.

  3. RP WRAP-UP — SLAB lines 100% complete in the General List but not
       fully billed: waiting on punch, but it must be chased to get paid.
       FTW lines are ignored — the General List's 100% column is slab-only
       (the FTW completion section isn't used). Read from the WIP workbook's
       'Test - RP' tab (rp_wip_reader output — run the WIP readers first).

OUTPUT
  ~/Documents/CompanyHealth/Money Bleeds.xlsx  (chmod 600 after write)
  Plain white/black formatting per repo rules. READ-ONLY everywhere else:
  QBO reads, WIP workbook reads, volume folder scans — no writes.

USAGE
  python3 health-dashboard/money_bleeds.py
  python3 health-dashboard/money_bleeds.py --out /path/x.xlsx
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import stat
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.formatting.rule import CellIsRule, ColorScaleRule, DataBarRule
from openpyxl.utils import get_column_letter

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from shared import paths
from shared import qbo_api
from shared import draws
from shared.qbo_cache import QboCache
from shared import rp_billing

# ────────────────────────── config / paths ──────────────────────────

DEFAULT_OUTPUT = paths.companyhealth_sources_dir() / "Money Bleeds.xlsx"

WIP_EXCEL_PATH = paths.get_path(
    "WIP_EXCEL_PATH",
    paths.onedrive_base() / "Company Files - WIP Report/WIP - MASTER new.xlsx",
)
# Bill Tracker (AP) — generated by bill-tracker/ via `sync-ap`. We READ it, we
# never recompute AP here (the user 2026-07-17: that info already lives there).
# MUST use the same path key/default as bill-tracker/excel_bill_sync.py — the
# canonical file lives in OneDrive/Automations-, NOT the old CompanyHealth copy
# (the user 2026-07-24: we were reading a 7-week-stale duplicate).
BILL_TRACKER_PATH = paths.get_path(
    "ACB_BILL_TRACKER_XLSX", paths.onedrive_base() / "Automations-/Bill Tracker.xlsx")
MFD_ROOT = paths.get_path(
    "MFD_PROJECTS_DIR",
    "/Volumes/Multi Family/MULTY FAMILY DIVISION PROJECTS",
)
CP_ACTIVE_DIR = paths.get_path(
    "CP_ACTIVE_DIR",
    "/Volumes/Common/CURRENT PROJECTS/Awarded Projects Commercial projects",
)

MASTER_SHEET = "WIP Master"          # header row 3, data 4+ (col A proj, B name)
RP_TEST_SHEET = "Test - RP"          # rp_wip_reader output (header row 1)

# 'MFD177 - JPI MERRITT PARK' → MFD177 ; \b keeps MFD1770 from matching MFD177
_MFD_FOLDER_RE = re.compile(r"^(MFD\d{3,4})\b", re.IGNORECASE)
_CP_FOLDER_RE = re.compile(r"^(CP\d{3,4})\b", re.IGNORECASE)
# Draw folder naming varies per project: '13- JULY 2026 DRAW' (MFD177) vs
# '6-JULY DRAW 2026' / '2-FEB DRAW 2026' (MFD192/325). Parse tolerantly:
# leading sequence number, then a month name + 4-digit year anywhere.
_MFD_DRAW_NUM_RE = re.compile(r"^\s*(\d{1,2})\s*-")
_YEAR_RE = re.compile(r"\b(20\d{2})\b")
_MONTHS = {m.upper(): i + 1 for i, m in enumerate(
    ["January", "February", "March", "April", "May", "June", "July",
     "August", "September", "October", "November", "December"])}
_MONTHS.update({m.upper(): i + 1 for i, m in enumerate(
    ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
     "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"])})


def _month_from_token(token: str) -> Optional[int]:
    """'JUNE'/'FEB'/'SEPT'/'MARZO' → month number. Abbreviations are any
    ≥3-char prefix of a full month name (English or Spanish)."""
    t = token.strip().upper()
    if len(t) < 3:
        return None
    for name, num in _MONTHS.items():
        if name.startswith(t):
            return num
    return None


def _parse_mfd_draw_name(name: str) -> Optional[Tuple[int, int, int]]:
    """'6-JULY DRAW 2026' / '12- JUNE 2026 DRAW' → (num, month, year)."""
    m = _MFD_DRAW_NUM_RE.match(name)
    if not m:
        return None
    y = _YEAR_RE.search(name)
    if not y:
        return None
    for token in re.findall(r"[A-Za-z]+", name):
        month = _month_from_token(token)
        if month:
            return int(m.group(1)), month, int(y.group(1))
    return None

_SKIP_DIRS = {"#recycle", "@eadir", "completed jobs", "z - non active or bidding"}

# Lien clock (Texas Prop. Code Ch. 53, first-tier subcontractor):
#   commercial notice = 15th of the 3rd month after the work month
#   residential       = 15th of the 2nd month
NOTICE_MONTHS = {"MFD": 3, "CP": 3, "RP": 2}
URGENT_DAYS = 15
WATCH_DAYS = 45

_RETAINAGE_RE = re.compile(r"retainage|retention|retenci[oó]n", re.IGNORECASE)

# Equipment leases / note payments invoiced to subs are NOT construction
# income (the user 2026-07-16) — no lien rights ride on them. Matched on
# line items + descriptions ('Other Charges:Equipment Lease', 'Note
# Principal Payment', 'Interest fee', 'Pump #14', 'Tractor #179', …).
_NON_CONSTRUCTION_RE = re.compile(
    r"equipment lease|monthly equipment|note principal|principal payment"
    r"|interest (charge|fee)|lease payment", re.IGNORECASE)
_EQUIP_ITEM_RE = re.compile(
    r"^(pump|tractor|truck|dump truck|trailer|excavator|other charges)\b",
    re.IGNORECASE)

CP_TOLERANCE = 1.0   # $ tolerance G702 earned vs QBO invoiced


# ────────────────────────── small helpers ──────────────────────────

def _today() -> dt.date:
    return dt.date.today()


def _add_months(year: int, month: int, n: int) -> Tuple[int, int]:
    m = month - 1 + n
    return year + m // 12, m % 12 + 1


def _roll_back_weekend(d: dt.date) -> dt.date:
    """Statute rule: deadlines roll BACKWARD to the prior business day,
    never forward. (Holidays not modeled — weekend-only.)"""
    while d.weekday() >= 5:          # 5=Sat, 6=Sun
        d -= dt.timedelta(days=1)
    return d


def notice_deadline(work_year: int, work_month: int, division: str) -> dt.date:
    n = NOTICE_MONTHS.get(division, NOTICE_MONTHS["RP"])   # unknown → shorter clock
    y, m = _add_months(work_year, work_month, n)
    return _roll_back_weekend(dt.date(y, m, 15))


def _division(customer_name: str) -> str:
    """Division from the invoice's customer name. MFD = parent customer
    'Multi Family' (never the Class field); else project-# prefix."""
    name = customer_name or ""
    if name.strip().lower().startswith("multi family"):
        return "MFD"
    proj = qbo_api.extract_proj(name)
    if proj:
        return "MFD" if proj.startswith("MFD") else ("CP" if proj.startswith("CP") else "RP")
    return "?"


def _parent(customer_name: str) -> str:
    """'Multi Family:MFD177 JPI Merritt Park' → 'Multi Family'; top-level
    customers have no parent."""
    return customer_name.split(":")[0].strip() if ":" in (customer_name or "") else ""


def _is_retainage_invoice(inv: dict) -> bool:
    texts = [inv.get("PrivateNote") or "",
             (inv.get("CustomerMemo") or {}).get("value") or ""]
    for line in inv.get("Line", []) or []:
        texts.append(line.get("Description") or "")
    return any(_RETAINAGE_RE.search(t) for t in texts if t)


def _is_lease_invoice(inv: dict) -> bool:
    """Equipment lease / note-payment invoices to subs — not construction
    income. Text match first; else every itemized line is an equipment or
    'Other Charges' item."""
    items, texts = [], []
    for line in inv.get("Line", []) or []:
        det = line.get("SalesItemLineDetail") or {}
        item = (det.get("ItemRef") or {}).get("name") or ""
        if item:
            items.append(item)
        if line.get("Description"):
            texts.append(line["Description"])
    if any(_NON_CONSTRUCTION_RE.search(t) for t in items + texts):
        return True
    return bool(items) and all(_EQUIP_ITEM_RE.match(i) for i in items)


def _parse_date(s: str) -> Optional[dt.date]:
    try:
        return dt.date.fromisoformat(s)
    except (TypeError, ValueError):
        return None


# ────────────────── check 1a — MFD draws vs invoices ────────────────

def read_active_mfd(wip_path: Path) -> List[Tuple[str, str]]:
    """MFD#### rows from the 'WIP Master' tab — the master sheet IS the MFD
    source for active jobs (same rule as wip/master_wip_test.py)."""
    wb = load_workbook(wip_path, data_only=True, read_only=True)
    ws = wb[MASTER_SHEET]
    out = []
    for r in range(4, ws.max_row + 1):
        proj = ws.cell(r, 1).value
        if proj and str(proj).strip().upper().startswith("MFD"):
            out.append((str(proj).strip().upper(),
                        str(ws.cell(r, 2).value or "").strip()))
    wb.close()
    return out


def find_mfd_project_folder(proj: str) -> Optional[Path]:
    """<MFD root>/<CLIENT>/<MFD### - NAME>. Scans client dirs (skipping
    recycle/completed/non-active); word-boundary match so MFD177 never
    matches MFD1770."""
    want = re.compile(rf"^{re.escape(proj)}\b", re.IGNORECASE)
    try:
        clients = [d for d in MFD_ROOT.iterdir() if d.is_dir()
                   and d.name.strip().lower() not in _SKIP_DIRS]
    except OSError:
        return None
    for client in clients:
        try:
            for sub in client.iterdir():
                if sub.is_dir() and want.match(sub.name.strip()):
                    return sub
        except OSError:
            continue
    return None


def find_mfd_draws_folder(project_folder: Path) -> Optional[Path]:
    """'PM MISC/DRAWS' first (the standard layout), else any 'Draw(s)' dir
    within two levels."""
    direct = project_folder / "PM MISC" / "DRAWS"
    if direct.is_dir():
        return direct
    for depth1 in project_folder.iterdir():
        if not depth1.is_dir():
            continue
        if draws.DRAWS_FOLDER_RE.match(depth1.name.strip()):
            return depth1
        try:
            for depth2 in depth1.iterdir():
                if depth2.is_dir() and draws.DRAWS_FOLDER_RE.match(depth2.name.strip()):
                    return depth2
        except OSError:
            continue
    return None


# An MFD draw folder holds the pay application AND the lien releases that ride
# along with it. The releases are named for what they are ('Conditional Release
# … August Draw 2026'), so the release test runs FIRST — otherwise a release
# carrying the word 'Draw' would masquerade as the draw itself.
_MFD_RELEASE_RE = re.compile(r"release|waiver|lien", re.IGNORECASE)
_MFD_DRAWDOC_RE = re.compile(r"draw|pay\s*app", re.IGNORECASE)


def mfd_draw_documents(draw_folder: Path) -> List[str]:
    """The pay-application PDFs inside a draw folder (recursing, because a job
    billing several contracts files one draw per contract subfolder).

    MFD draws are PDFs — there is no G702 to read an amount off, so the
    presence of the draw document IS the signal that the draw was actually
    built and sent. A folder holding only conditional/unconditional releases
    is a placeholder opened ahead of the billing, not money we can invoice."""
    docs: List[str] = []
    try:
        entries = list(draw_folder.rglob("*"))
    except OSError:
        return docs
    for f in entries:
        try:
            if not f.is_file() or f.suffix.lower() != ".pdf":
                continue
        except OSError:
            continue
        if _MFD_RELEASE_RE.search(f.name):
            continue
        if _MFD_DRAWDOC_RE.search(f.name):
            docs.append(f.name)
    return sorted(docs)


def scan_mfd_draws(draws_dir: Path):
    """(built, staged) for a project's DRAWS folder.

    built  = highest-numbered draw folder that holds a pay application —
             the latest real draw, and the only one we test for an invoice.
    staged = a higher-numbered folder that exists but holds no draw document
             yet (placeholder opened ahead of the work). Reported, never
             judged: there is nothing to invoice until the draw is built.

    Deliberately only the latest draw of each kind — older draws are left
    alone because the pre-2026 folders don't follow this naming."""
    folders = []
    try:
        entries = list(draws_dir.iterdir())
    except OSError:
        return None, None
    for entry in entries:
        if not entry.is_dir():
            continue
        parsed = _parse_mfd_draw_name(entry.name)
        if not parsed:
            continue
        num, month, year = parsed
        folders.append((num, dt.date(year, month, 1), entry.name.strip(),
                        mfd_draw_documents(entry)))
    if not folders:
        return None, None
    folders.sort(key=lambda f: f[0])
    built = next((f for f in reversed(folders) if f[3]), None)
    top = folders[-1]
    staged = top if (not top[3] and (built is None or top[0] > built[0])) else None
    return built, staged


def check_mfd_draws(qc: QboCache,
                    proj_map: Dict[str, dict]) -> List[Dict[str, Any]]:
    """One row per active MFD project: the latest BUILT draw (the folder
    holding an actual pay application) vs latest QBO invoice date. PASS =
    latest invoice lands in/after that draw's month. A higher-numbered
    placeholder folder is reported in STAGED NEXT, never judged."""
    results = []
    today = _today()
    for proj, name in read_active_mfd(WIP_EXCEL_PATH):
        row = {"project": proj, "name": name, "draw": "", "draw_month": None,
               "staged": "", "last_invoice": None, "verdict": "", "detail": ""}
        results.append(row)

        folder = find_mfd_project_folder(proj)
        if folder is None:
            row["verdict"] = "REVIEW"
            row["detail"] = "No project folder found on the Multi Family volume"
            continue
        draws_dir = find_mfd_draws_folder(folder)
        if draws_dir is None:
            row["verdict"] = "REVIEW"
            row["detail"] = f"No DRAWS folder under {folder.name}"
            continue
        built, staged = scan_mfd_draws(draws_dir)
        if staged is not None:
            row["staged"] = f"{staged[2]} — folder only, no draw doc yet"
        if built is None:
            row["verdict"] = "REVIEW"
            row["detail"] = ("No built draw in the DRAWS folder — "
                             + (f"{staged[2]} is staged but holds no pay application"
                                if staged is not None
                                else "no numbered draw subfolders"))
            continue
        draw_num, draw_month, draw_label, draw_docs = built
        row["draw"] = draw_label
        row["draw_month"] = draw_month

        cust = proj_map.get(proj)
        if cust is None:
            row["verdict"] = "RED"
            row["detail"] = "No QBO project customer matches this project #"
            continue
        invs = qc.invoices_for_customer(cust["id"])
        last = max((_parse_date(i.get("TxnDate")) for i in invs
                    if _parse_date(i.get("TxnDate"))), default=None)
        row["last_invoice"] = last

        docs = f"{len(draw_docs)} pay app(s)" if draw_docs else "pay app"
        if last is not None and last >= draw_month:
            row["verdict"] = "PASS"
            row["detail"] = f"Draw {draw_num} ({docs}) invoiced ({last.isoformat()})"
        elif (draw_month.year, draw_month.month) == (today.year, today.month):
            row["verdict"] = "PENDING"
            row["detail"] = (f"Draw {draw_num} is built ({docs}) and is "
                             f"current-month — invoice not in QBO yet")
        else:
            row["verdict"] = "RED"
            row["detail"] = (f"Draw {draw_num} ({draw_label}) is BUILT ({docs}) "
                             f"but has NO QBO invoice — last invoice "
                             f"{last.isoformat() if last else 'NEVER'}. INVOICE THIS.")
    return results


# ────────────────── check 1b — CP draws vs invoices ────────────────

def check_cp_draws(qc: QboCache,
                   proj_map: Dict[str, dict]) -> List[Dict[str, Any]]:
    """One row per active CP project folder that has a draw: G702
    earned-less-retainage (cumulative, what should be invoiced) vs the sum
    of ALL QBO invoices for the project. Shortfall = a draw never invoiced."""
    results = []
    try:
        folders = sorted(d for d in CP_ACTIVE_DIR.iterdir() if d.is_dir())
    except OSError as e:
        raise SystemExit(f"✗ CP active dir unreadable: {CP_ACTIVE_DIR} ({e})")
    for folder in folders:
        m = _CP_FOLDER_RE.match(folder.name.strip())
        if not m:
            continue
        proj = m.group(1).upper()
        found = draws.find_latest_draw(folder)
        if not found:
            continue                              # no draw yet — nothing to verify
        draw_num, draw_file = found
        row = {"project": proj, "name": folder.name, "draw_num": draw_num,
               "earned": None, "invoiced": None, "verdict": "", "detail": ""}
        results.append(row)

        data, flags = draws.read_draw_g702(draw_file)
        earned = (data or {}).get("earned_less_retainage")
        if earned is None:
            earned = (data or {}).get("billed")    # fallback: gross billed
        if earned is None:
            row["verdict"] = "REVIEW"
            row["detail"] = "; ".join(flags) or f"Draw #{draw_num} G702 unreadable"
            continue
        row["earned"] = earned

        cust = proj_map.get(proj)
        if cust is None:
            row["verdict"] = "RED"
            row["detail"] = "No QBO project customer matches this project #"
            continue
        invs = qc.invoices_for_customer(cust["id"])
        invoiced = sum(float(i.get("TotalAmt") or 0) for i in invs)
        row["invoiced"] = invoiced

        gap = earned - invoiced
        if gap > CP_TOLERANCE:
            row["verdict"] = "RED"
            row["detail"] = (f"Draw #{draw_num} earned ${earned:,.2f} but QBO "
                             f"invoiced ${invoiced:,.2f} — ${gap:,.2f} never invoiced")
        else:
            row["verdict"] = "PASS"
            row["detail"] = f"QBO invoiced covers draw #{draw_num}"
    return results


# ────────────────── check 2 — lien clock on open invoices ───────────

def check_lien_clock(qc: QboCache,
                     proj_map: Dict[str, dict]) -> Tuple[
        List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Every open invoice → notice deadline + days left. Work month =
    invoice month (the user 2026-07-16: RP invoices go out the day the job
    finishes; draws bill their work month). Returns (monthly_rows,
    retainage_rows, lease_rows) — retainage runs its own statutory track;
    equipment-lease/note invoices aren't construction income at all."""
    today = _today()
    monthly, retainage, leases = [], [], []
    for inv in qc.open_invoices():
        txn = _parse_date(inv.get("TxnDate"))
        if txn is None:
            continue
        cust_name = (inv.get("CustomerRef") or {}).get("name") or ""
        div = _division(cust_name)
        proj = qbo_api.extract_proj(cust_name) or ""
        # Invoice CustomerRef.name is the bare display name — the parent
        # chain comes from the customer map's FullyQualifiedName.
        parent = _parent(cust_name)
        if not parent and proj and proj in proj_map:
            fqn = proj_map[proj].get("fully_qualified_name", "")
            parent = ":".join(fqn.split(":")[:-1])
        row = {
            "division": div if div != "?" else "? (review)",
            "project": proj,
            "parent": parent,
            "customer": cust_name,
            "doc": inv.get("DocNumber") or "",
            "txn_date": txn,
            "balance": float(inv.get("Balance") or 0),
        }
        if _is_lease_invoice(inv):
            row["note"] = "Equipment lease / note payment — not construction income"
            leases.append(row)
            continue
        if _is_retainage_invoice(inv):
            row["note"] = ("Retainage — separate track (§ 53.057, keyed to "
                           "completion, not the monthly clock)")
            retainage.append(row)
            continue
        deadline = notice_deadline(txn.year, txn.month, div if div != "?" else "RP")
        days = (deadline - today).days
        row["work_month"] = dt.date(txn.year, txn.month, 1)
        row["deadline"] = deadline
        row["days_left"] = days
        row["status"] = ("PAST" if days < 0 else
                         "URGENT" if days <= URGENT_DAYS else
                         "WATCH" if days <= WATCH_DAYS else "OK")
        monthly.append(row)
    # Don't show OK rows — the sheet is a deadline watchlist, not a ledger
    # (the user 2026-07-17). Only PAST / URGENT / WATCH earn a line.
    monthly = [r for r in monthly if r["status"] != "OK"]
    monthly.sort(key=lambda r: r["days_left"])
    retainage.sort(key=lambda r: r["txn_date"])
    leases.sort(key=lambda r: -r["balance"])
    return monthly, retainage, leases


# ────────────────── check 4 — unused POs ≥30 days old ───────────────

PO_STALE_DAYS = 30


def check_unused_pos(qc: QboCache) -> List[Dict[str, Any]]:
    """Open QBO purchase orders with NO bill linked, aged ≥30 days — money
    committed on paper that never got used (or a bill that never got entered
    against it). Newest first within the flagged set, by value."""
    today = _today()
    rows = []
    for po in qc.purchase_orders():
        if po.get("POStatus") != "Open":   # POStatus isn't queryable — filter here
            continue
        if po.get("LinkedTxn"):            # a bill/other txn already references it
            continue
        txn = _parse_date(po.get("TxnDate"))
        if txn is None:
            continue
        age = (today - txn).days
        if age < PO_STALE_DAYS:
            continue
        # cost code / job from the first line's customer + description
        job = ""
        for line in po.get("Line", []) or []:
            det = line.get("ItemBasedExpenseLineDetail") or \
                line.get("AccountBasedExpenseLineDetail") or {}
            cust = (det.get("CustomerRef") or {}).get("name") or ""
            job = qbo_api.extract_proj(cust) or job
            if job:
                break
        rows.append({
            "doc": str(po.get("DocNumber") or ""),
            "txn_date": txn,
            "age": age,
            "vendor": (po.get("VendorRef") or {}).get("name") or "",
            "project": job,
            "amount": float(po.get("TotalAmt") or 0),
            "memo": (po.get("Memo") or "")[:80],
        })
    rows.sort(key=lambda r: -r["amount"])
    return rows


# ────────────────── check 5 — open bills (AP) from Bill Tracker ─────
# READ-ONLY off the Bill Tracker workbook (bill-tracker/ owns the matching:
# each bill → the GC invoice that authorizes payment + client payment date).
# We only re-bucket it here (the user 2026-07-17):
#   AR spine — paid by client / client not paid / no invoice issued yet
#   crossed with the SUB's lien clock (a sub can lien us if unpaid): a bill is
#   "lien coming up" when the sub's notice deadline is within the current cycle.
# "Money out by this month's lien-15" = the paid-by-client, not-yet-due bucket.

BILL_LIEN_WINDOW = 45           # days-out that counts as "coming up"
BILL_LIEN_GRACE = 15            # just-passed deadlines still count (pay now)


def _ar_state(minv, pdate) -> str:
    if minv and pdate:
        return "paid"           # client already paid us for this work
    if minv:
        return "unpaid"         # invoiced the GC, not collected yet
    return "noinv"              # not even billed to the GC


def _bill_lien(division: str, bill_date, today: dt.date):
    """The sub's lien deadline on this bill (work month ≈ bill date). Returns
    (deadline, days_left, state) — state in due/far/expired/n-a."""
    div = (division or "").upper()
    if div not in ("RP", "CP", "MFD") or not bill_date:
        return None, None, "n/a"
    bd = bill_date.date() if isinstance(bill_date, dt.datetime) else bill_date
    deadline = notice_deadline(bd.year, bd.month, div)
    days = (deadline - today).days
    if days < -BILL_LIEN_GRACE:
        state = "expired"       # sub's lien window closed — lower urgency
    elif days <= BILL_LIEN_WINDOW:
        state = "due"           # coming up (pay before they can lien)
    else:
        state = "far"
    return deadline, days, state


def read_open_bills(path: Path) -> Tuple[List[Dict[str, Any]], str]:
    """Open (unpaid-to-sub) bills from the Bill Tracker 'Bills' sheet,
    aggregated to bill level, tagged with AR state + lien state. Returns
    (rows, tracker_synced)."""
    from datetime import datetime as _dtm
    synced = ""
    try:
        synced = _dtm.fromtimestamp(path.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
    except OSError:
        pass
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb["Bills"]
    it = ws.iter_rows(values_only=True)
    # the header row moved: the newer bill-tracker puts section bands on row 1
    # and the real headers on row 2 — detect it (the user 2026-07-24).
    idx: Dict[str, int] = {}
    for _ in range(6):
        try:
            row = next(it)
        except StopIteration:
            break
        names = [str(c).strip() if c is not None else "" for c in row]
        if "Vendor" in names and "Bill Open Bal" in names:
            idx = {n: i for i, n in enumerate(names) if n}
            break
    if not idx:
        wb.close()
        return [], synced

    # The Bill Tracker renames columns as it evolves ("Payment Date" → "GC Paid
    # Date", "Status" → "Pay Status" on 2026-07-28). Accept known aliases so a
    # rename degrades to nothing worse than a blank, never a silent $0 bucket.
    ALIASES = {
        "Payment Date": ("Payment Date", "GC Paid Date"),
        "Status": ("Status", "Pay Status", "Invoice Status"),
        "Matched Invoice": ("Matched Invoice", "Invoice #"),
    }

    def cell(row, name):
        for cand in ALIASES.get(name, (name,)):
            i = idx.get(cand)
            if i is not None and i < len(row) and row[i] not in (None, ""):
                return row[i]
        i = idx.get(name)
        return row[i] if i is not None and i < len(row) else None

    today = _today()
    bills: Dict[Any, Dict[str, Any]] = {}
    for row in it:
        vendor = cell(row, "Vendor")
        billno = cell(row, "Bill #")
        if not vendor:
            continue
        key = (vendor, billno)
        if key in bills:
            continue                        # bill-level fields repeat per line
        openbal = float(cell(row, "Bill Open Bal") or 0)
        if openbal <= 0:                    # already paid to the sub — skip
            continue
        division = cell(row, "Division")
        bdate = cell(row, "Bill Date")
        minv = cell(row, "Matched Invoice")
        pdate = cell(row, "Payment Date")
        deadline, days, lien_state = _bill_lien(division, bdate, today)
        note = str(cell(row, "Line Description") or "")
        bills[key] = {
            "vendor": str(vendor), "bill": str(billno or ""),
            "date": bdate.date() if isinstance(bdate, dt.datetime) else bdate,
            "division": division or "?", "project": str(cell(row, "Project #") or ""),
            "open": openbal,
            "invoice": str(minv or ""),
            "invoice_date": cell(row, "Invoice Date"),
            "paid_date": pdate.date() if isinstance(pdate, dt.datetime) else pdate,
            "status": str(cell(row, "Status") or ""),
            "ar": _ar_state(minv, pdate),
            "deadline": deadline, "days": days, "lien": lien_state,
            "note": note[:60],
        }
    wb.close()
    return list(bills.values()), synced


# ────────────────── check 3 — RP wrap-up (waiting on punch) ─────────

def check_rp_wrapup(wip_path: Path) -> Tuple[List[Dict[str, Any]], str]:
    """'Test - RP' SLAB rows 100% complete in the General List but not fully
    billed — waiting on punch, chase to get paid. FTW lines are skipped: the
    General List's 100% column is slab-only; the FTW completion section
    isn't used (the user 2026-07-16). Returns (rows, synced)."""
    wb = load_workbook(wip_path, data_only=True, read_only=True)
    ws = wb[RP_TEST_SHEET]
    # FIND the header row — never assume row 1 (2026-08-03). The tab grew a
    # title block, so the header sits below it and a hard-coded row 1 read
    # silently returned nothing at all.
    hdr_row = next((r for r in range(1, 16)
                    if any(str(ws.cell(r, c).value or "").strip().upper()
                           == "PROJECT #"
                           for c in range(1, (ws.max_column or 0) + 1))), None)
    if hdr_row is None:
        wb.close()
        return [], ""
    hdr = {str(ws.cell(hdr_row, c).value or "").strip().upper(): c
           for c in range(1, ws.max_column + 1)}

    def col(r, label):
        c = hdr.get(label)
        return ws.cell(r, c).value if c else None

    # LAST SYNCED left the lean 'Test - RP' layout (2026-08-07); fall back to
    # the report date on the title row (B2: "REPORT DATE: …").
    synced = ""
    for rr in range(1, hdr_row):
        v = str(ws.cell(rr, 2).value or "")
        if "REPORT DATE" in v.upper():
            synced = v.split(":", 1)[-1].strip()
            break
    rows = []
    for r in range(hdr_row + 1, ws.max_row + 1):
        proj = col(r, "PROJECT #")
        if not proj:
            continue
        synced = str(col(r, "LAST SYNCED") or synced)
        proj = str(proj).strip().upper()
        if proj.endswith("-FTW"):
            continue                      # 100% is slab-only — FTW ignored
        notes = str(col(r, "NOTES") or "")
        status = str(col(r, "STATUS") or "").strip()
        if "100% complete (list)" not in notes or status.lower() != "active":
            continue
        # TOTAL CONTRACT PRICE is a live formula on this tab (so the owner's
        # edits add up in Excel), and an openpyxl-written formula has no cached
        # value — fall back to its components, which are always plain numbers.
        contract = float(col(r, "TOTAL CONTRACT PRICE")
                         or (float(col(r, "ORIGINAL CONTRACT") or 0)
                             + float(col(r, "APPROVED COs") or 0)))
        billed = float(col(r, "BILLED TO DATE") or 0)
        left = float(col(r, "LEFT TO BILL") or (contract - billed))
        if left <= 0:
            continue
        # WHY: the classification segment, minus the RED echo + the 100% tag
        why = "; ".join(
            s.strip() for s in notes.split(";")
            if s.strip() and not s.strip().startswith("RED:")
            and s.strip() != "100% complete (list)") or notes
        rows.append({"project": proj, "name": str(col(r, "PROJECT NAME") or ""),
                     "client": str(col(r, "CLIENT") or ""),
                     "contract": contract, "billed": billed, "left": left,
                     "note": why})
    wb.close()
    rows.sort(key=lambda x: -x["left"])
    return rows, synced


# ────────────────────────── Excel output ─────────────────────────────
# Full color + conditional formatting per the user's explicit, repeated ask
# (2026-07-16/17): read at a glance — grouped sections, banded rows, data
# bars, color scales, bold. This workbook is exempt from the plain-Excel rule.

CUR = '#,##0'
_BOLD = Font(bold=True)
_WHITE = Font(bold=True, color="FFFFFF")

# palette
C_NAVY = "1F3864"       # header
C_ZEBRA = "EEF3FA"      # banded row
C_SUB = "D9E1F2"        # subtotal row
_HDR_FILL = PatternFill("solid", fgColor=C_NAVY)
_ZEBRA = PatternFill("solid", fgColor=C_ZEBRA)
_SUB_FILL = PatternFill("solid", fgColor=C_SUB)
_RED_FONT = Font(bold=True, color="9C0006")
_AMB_FONT = Font(bold=True, color="9C6500")
_GRN_FONT = Font(bold=True, color="006100")

# section-band header fills (white bold text on a saturated color)
_BAND = {
    "PAST":   "C00000", "URGENT": "ED7D31", "WATCH": "FFC000",
    "MFD":    "305496", "CP":     "1F6B4C", "RP":    "7030A0",
    "RETAIN": "548235", "LEASE":  "808080", "PO":    "BF8F00",
}
# per-status cell fills for the verdict/status column
_STATUS_FILL = {
    "PASS": "C6EFCE", "OK": "C6EFCE",
    "PENDING": "FFEB9C", "WATCH": "FFEB9C", "REVIEW": "FFEB9C",
    "RED": "FFC7CE", "PAST": "FFC7CE", "URGENT": "FFC7CE",
}
_THIN = Side(style="thin", color="D0D7E5")
_BORDER = Border(left=_THIN, right=_THIN, top=_THIN, bottom=_THIN)


def _sheet(wb: Workbook, title: str, headers: List[str], widths: List[int]):
    ws = wb.create_sheet(title)
    ws.append(headers)
    for c in range(1, len(headers) + 1):
        cell = ws.cell(1, c)
        cell.font = _WHITE
        cell.fill = _HDR_FILL
        cell.border = _BORDER
        cell.alignment = Alignment(vertical="center", wrap_text=True,
                                   horizontal="center")
    for i, w in enumerate(widths):
        ws.column_dimensions[get_column_letter(i + 1)].width = w
    ws.row_dimensions[1].height = 28
    ws.freeze_panes = "A2"
    return ws


def _band_row(ws, ncols: int, label: str, color: str) -> None:
    """A full-width colored section header inside a sheet."""
    ws.append([label] + [""] * (ncols - 1))
    r = ws.max_row
    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=ncols)
    c = ws.cell(r, 1)
    c.fill = PatternFill("solid", fgColor=color)
    c.font = Font(bold=True, color="FFFFFF", size=11)
    c.alignment = Alignment(vertical="center", indent=1)
    ws.row_dimensions[r].height = 20


def _zebra(ws, ncols: int, idx: int, money_cols=(), status_col=0,
           status="") -> None:
    """Border + banding on the just-appended data row; money cols formatted;
    optional status-cell fill."""
    r = ws.max_row
    shade = _ZEBRA if idx % 2 else None
    for c in range(1, ncols + 1):
        cell = ws.cell(r, c)
        cell.border = _BORDER
        if shade:
            cell.fill = shade
    for c in money_cols:
        ws.cell(r, c).number_format = CUR
    if status_col and status in _STATUS_FILL:
        sc = ws.cell(r, status_col)
        sc.fill = PatternFill("solid", fgColor=_STATUS_FILL[status])
        sc.font = _BOLD


def _subtotal(ws, ncols: int, label_col: int, label: str,
              amount_col: int, amount: float) -> None:
    ws.append([""] * ncols)
    r = ws.max_row
    for c in range(1, ncols + 1):
        ws.cell(r, c).fill = _SUB_FILL
        ws.cell(r, c).border = _BORDER
    ws.cell(r, label_col, label).font = _BOLD
    a = ws.cell(r, amount_col, amount)
    a.number_format = CUR
    a.font = _BOLD


def _data_bar(ws, col: int, r1: int, r2: int, color="8EAADB") -> None:
    if r2 >= r1:
        L = get_column_letter(col)
        ws.conditional_formatting.add(
            f"{L}{r1}:{L}{r2}",
            DataBarRule(start_type="num", start_value=0, end_type="max",
                        color=color, showValue=True))


def _color_scale(ws, col: int, r1: int, r2: int, low_is_bad=True) -> None:
    if r2 < r1:
        return
    L = get_column_letter(col)
    red, grn = "F8696B", "63BE7B"
    lo, hi = (red, grn) if low_is_bad else (grn, red)
    ws.conditional_formatting.add(
        f"{L}{r1}:{L}{r2}",
        ColorScaleRule(start_type="min", start_color=lo,
                       mid_type="percentile", mid_value=50, mid_color="FFEB84",
                       end_type="max", end_color=hi))


def _verdict_cf(ws, col: int, r1: int, r2: int) -> None:
    """Highlight-rule the verdict/status text so filtering/sorting keeps color."""
    if r2 < r1:
        return
    L = get_column_letter(col)
    rng = f"{L}{r1}:{L}{r2}"
    for words, fill in (
        (("RED", "PAST", "URGENT"), "FFC7CE"),
        (("REVIEW", "PENDING", "WATCH"), "FFEB9C"),
        (("PASS", "OK"), "C6EFCE"),
    ):
        for w in words:
            ws.conditional_formatting.add(
                rng, CellIsRule(operator="equal", formula=[f'"{w}"'],
                                fill=PatternFill("solid", fgColor=fill)))


def _subband_row(ws, ncols: int, label: str, color: str) -> None:
    """A lighter sub-section header inside a group."""
    ws.append([label] + [""] * (ncols - 1))
    r = ws.max_row
    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=ncols)
    c = ws.cell(r, 1)
    c.fill = PatternFill("solid", fgColor=color)
    c.font = Font(bold=True, italic=True, color="404040")
    c.alignment = Alignment(vertical="center", indent=2)


def _finish(ws, ncols: int, header_row=1) -> None:
    ws.auto_filter.ref = f"A{header_row}:{get_column_letter(ncols)}{ws.max_row}"


def _write_open_bills(wb, bills: List[dict], synced: str) -> None:
    """One sheet: AP bills that need money to go out, grouped by AR state
    (paid by client / not paid / not invoiced), each split lien-coming-up vs
    not (the user 2026-07-17). Sub who billed us can lien us → pay the
    coming-up ones before the deadline; the paid-by-client not-yet-due bunch
    is 'money out by this month's lien-15'."""
    cols = ["LIEN", "SUB LIEN DEADLINE", "DAYS", "SUB (VENDOR)", "DIV",
            "PROJECT #", "BILL #", "BILL DATE", "OPEN BAL $", "GC INVOICE",
            "CLIENT PAID", "STATUS"]
    ws = _sheet(wb, "Open Bills (AP)", cols,
                [10, 16, 7, 26, 6, 11, 12, 12, 15, 12, 12, 24])

    groups = [
        ("paid",   "PAID BY CLIENT — money is in, pay it out", "BF8F00"),
        ("unpaid", "CLIENT HASN'T PAID US — owe the sub, collect from the GC", "C00000"),
        ("noinv",  "NO INVOICE ISSUED YET — bill the GC first", "7030A0"),
    ]
    for ar, title, color in groups:
        grp = [b for b in bills if b["ar"] == ar]
        if not grp:
            continue
        gtot = sum(b["open"] for b in grp)
        _band_row(ws, 12, f"  {title}   —   {len(grp)} bill(s)   —   "
                          f"${gtot:,.0f} to go out", color)
        g_start = ws.max_row + 1
        # split: lien coming up (due) first, then the rest
        for sub_key, sub_label, sub_color in (
            ("due",  "coming up for lien — pay before the deadline", "FCE4D6"),
            ("rest", "not due for lien — clear by this month's 15th", "EDEDED"),
        ):
            part = [b for b in grp if (b["lien"] == "due") == (sub_key == "due")]
            if not part:
                continue
            part.sort(key=lambda b: (b["days"] if b["days"] is not None else 9999,
                                     -b["open"]))
            _subband_row(ws, 12, f"    {sub_label}  ·  {len(part)} bill(s)  ·  "
                                 f"${sum(b['open'] for b in part):,.0f}", sub_color)
            s1 = ws.max_row + 1
            for i, b in enumerate(part):
                lien_tag = {"due": "DUE", "expired": "expired",
                            "far": "", "n/a": "n/a"}[b["lien"]]
                ws.append([
                    lien_tag,
                    b["deadline"].isoformat() if b["deadline"] else "—",
                    b["days"] if b["days"] is not None else "",
                    b["vendor"], b["division"], b["project"], b["bill"],
                    b["date"].isoformat() if b["date"] else "—",
                    b["open"], b["invoice"],
                    b["paid_date"].isoformat() if b["paid_date"] else "—",
                    b["status"],
                ])
                status = "URGENT" if b["lien"] == "due" else ""
                _zebra(ws, 12, i, money_cols=(9,), status_col=1, status=status)
                ws.row_dimensions[ws.max_row].outlineLevel = 1
            _data_bar(ws, 9, s1, ws.max_row)
            _subtotal(ws, 12, 8, "subtotal", 9, sum(b["open"] for b in part))
        # group total
        _subtotal(ws, 12, 8, f"{title.split(' —')[0]} TOTAL", 9, gtot)
        ws.cell(ws.max_row, 8).font = Font(bold=True, size=11)
    _finish(ws, 12)
    ws.sheet_properties.tabColor = "C55A11"
    note = ("Source: Bill Tracker.xlsx (bill-tracker / sync-ap) — read-only, "
            f"last synced {synced or 'unknown'}. Lien = the SUB's deadline to "
            "lien us (work month ≈ bill date; RP 15th of 2nd month, CP/MFD 3rd).")
    ws.append([]); ws.append([note])
    ws.cell(ws.max_row, 1).font = Font(italic=True, color="808080")


def write_workbook(out: Path,
                   mfd: List[dict], cp: List[dict],
                   lien: List[dict], reten: List[dict], leases: List[dict],
                   rp: dict, pos: List[dict],
                   bills: List[dict], bills_synced: str) -> None:
    wb = Workbook()
    dash = wb.active
    dash.title = "Dashboard"

    # ── Draws MFD ──
    ws = _sheet(wb, "Draws MFD", ["PROJECT #", "PROJECT NAME", "LATEST BUILT DRAW",
                                  "STAGED NEXT", "LAST QBO INVOICE", "VERDICT",
                                  "DETAIL"],
                [11, 30, 26, 34, 17, 11, 70])
    first = ws.max_row + 1
    for i, r in enumerate(mfd):
        ws.append([r["project"], r["name"], r["draw"], r.get("staged") or "—",
                   r["last_invoice"].isoformat() if r["last_invoice"] else "—",
                   r["verdict"], r["detail"]])
        _zebra(ws, 7, i, status_col=6, status=r["verdict"])
    _verdict_cf(ws, 6, first, ws.max_row)
    _finish(ws, 7)

    # ── Draws CP (data bar on the un-invoiced gap) ──
    ws = _sheet(wb, "Draws CP", ["PROJECT #", "FOLDER", "DRAW #",
                                 "G702 EARNED (LESS RET.) $", "QBO INVOICED $",
                                 "GAP $", "VERDICT", "DETAIL"],
                [11, 34, 8, 22, 16, 14, 11, 60])
    first = ws.max_row + 1
    for i, r in enumerate(cp):
        gap = (r["earned"] or 0) - (r["invoiced"] or 0)
        ws.append([r["project"], r["name"], r["draw_num"], r["earned"],
                   r["invoiced"], gap if gap > 0 else 0, r["verdict"], r["detail"]])
        _zebra(ws, 8, i, money_cols=(4, 5, 6), status_col=7, status=r["verdict"])
    last = ws.max_row
    _data_bar(ws, 6, first, last, color="F8696B")
    _verdict_cf(ws, 7, first, last)
    _finish(ws, 8)

    # ── Lien Clock — grouped by STATUS, banded, data bar $, color-scale days ──
    lcols = ["STATUS", "DAYS LEFT", "NOTICE DEADLINE", "DIVISION", "PARENT",
             "PROJECT #", "INVOICE #", "INVOICE DATE", "WORK MONTH",
             "OPEN BALANCE $", "CUSTOMER"]
    ws = _sheet(wb, "Lien Clock", lcols,
                [9, 10, 15, 10, 22, 11, 10, 12, 11, 15, 42])
    by_status: Dict[str, List[dict]] = {"PAST": [], "URGENT": [], "WATCH": []}
    for r in lien:
        by_status.get(r["status"], by_status["WATCH"]).append(r)
    for status in ("PAST", "URGENT", "WATCH"):
        grp = by_status[status]
        if not grp:
            continue
        tot = sum(r["balance"] for r in grp)
        _band_row(ws, 11, f"  {status}  —  {len(grp)} invoice(s)  —  "
                          f"${tot:,.0f} with no lien backup", _BAND[status])
        g1 = ws.max_row + 1
        for i, r in enumerate(grp):
            ws.append([r["status"], r["days_left"], r["deadline"].isoformat(),
                       r["division"], r["parent"], r["project"], r["doc"],
                       r["txn_date"].isoformat(),
                       r["work_month"].strftime("%b %Y"), r["balance"],
                       r["customer"]])
            _zebra(ws, 11, i, money_cols=(10,), status_col=1, status=status)
            ws.row_dimensions[ws.max_row].outlineLevel = 1
        g2 = ws.max_row
        _data_bar(ws, 10, g1, g2)
        _color_scale(ws, 2, g1, g2, low_is_bad=True)
        _subtotal(ws, 11, 9, f"{status} subtotal", 10, tot)
    _finish(ws, 11, header_row=1)

    # ── Lien Retainage ──
    ws = _sheet(wb, "Lien Retainage", ["DIVISION", "PARENT", "PROJECT #",
                                       "INVOICE #", "INVOICE DATE",
                                       "OPEN BALANCE $", "CUSTOMER", "NOTE"],
                [10, 22, 11, 10, 12, 15, 38, 52])
    first = ws.max_row + 1
    for i, r in enumerate(reten):
        ws.append([r["division"], r["parent"], r["project"], r["doc"],
                   r["txn_date"].isoformat(), r["balance"], r["customer"],
                   r["note"]])
        _zebra(ws, 8, i, money_cols=(6,))
    last = ws.max_row
    _data_bar(ws, 6, first, last, color="A9D08E")
    if reten:
        _subtotal(ws, 8, 5, "Total retainage", 6,
                  sum(r["balance"] for r in reten))
    _finish(ws, 8)

    # ── Leases (excluded) ──
    ws = _sheet(wb, "Leases (excluded)", ["PARENT", "CUSTOMER", "INVOICE #",
                                          "INVOICE DATE", "OPEN BALANCE $",
                                          "WHY EXCLUDED"],
                [22, 38, 10, 12, 15, 52])
    first = ws.max_row + 1
    for i, r in enumerate(leases):
        ws.append([r["parent"], r["customer"], r["doc"],
                   r["txn_date"].isoformat(), r["balance"], r["note"]])
        _zebra(ws, 6, i, money_cols=(5,))
    last = ws.max_row
    _data_bar(ws, 5, first, last, color="BFBFBF")
    if leases:
        _subtotal(ws, 6, 4, "Total excluded", 5,
                  sum(r["balance"] for r in leases))
    _finish(ws, 6)

    # ── RP Billing Status (poured & unbilled vs backlog) ──
    ws = _sheet(wb, "RP Billing Status",
                ["STATUS", "PROJECT #", "SCOPE", "ADDRESS", "BUILDER",
                 "BID $", "BILLED $", "DUE $", "DAYS SINCE POUR"],
                [13, 11, 7, 30, 24, 13, 13, 13, 15])
    for band, items, color, note in (
            ("POURED — NOT BILLED · INVOICE NOW", rp["invoice_now"], "C00000",
             "concrete is down; this is real underbilling"),
            ("DRAW / PHASE-BILLED — judged by the draw schedule", rp.get("draw_based", []),
             "BF8F00", "billing follows draws, not pour — NOT underbilling"),
            ("NOT POURED — BACKLOG (not owed)", rp["backlog"], "7F7F7F",
             "work still to come — excluded from underbilling")):
        if not items:
            continue
        _band_row(ws, 9, f"  {band}   —   {len(items)} scope(s)   —   "
                         f"${sum(r['gap'] for r in items):,.0f}   ·   {note}", color)
        first = ws.max_row + 1
        for i, r in enumerate(items):
            ws.append([("draw-based" if r.get("why") else
                        ("INVOICE NOW" if r["poured"] else "backlog")),
                       r["proj"], r["scope"], r["addr"], r["builder"],
                       r["bid"], r["billed"], r["gap"],
                       r["days"] if r["days"] is not None else ""])
            _zebra(ws, 9, i, money_cols=(6, 7, 8), status_col=1,
                   status="URGENT" if r["poured"] else "")
            ws.row_dimensions[ws.max_row].outlineLevel = 1
        _data_bar(ws, 8, first, ws.max_row,
                  color="F8696B" if items is rp["invoice_now"] else "BFBFBF")
        _subtotal(ws, 9, 5, "subtotal", 8, sum(r["gap"] for r in items))
    _finish(ws, 9)
    ws.append([])
    ws.append([f"Poured = the crew schedule shows this scope reaching "
               f"pour/wreck/stress/punch within the last {rp['weeks_back']} weeks. "
               f"Slab vs flatwork read from the stage text; billing compared per "
               f"scope (RP#### vs RP####-FTW). Gaps under ${rp_billing.FEE_TOLERANCE:,.0f} "
               f"are treated as billed out (builder fee / rounding)."])
    ws.cell(ws.max_row, 1).font = Font(italic=True, color="808080")

    ws = _sheet(wb, "Unused POs 30d+", ["P.O. #", "PO DATE", "AGE (days)",
                                        "VENDOR", "PROJECT #", "AMOUNT $",
                                        "MEMO"],
                [10, 12, 11, 30, 11, 15, 48])
    first = ws.max_row + 1
    for i, r in enumerate(pos):
        ws.append([r["doc"], r["txn_date"].isoformat(), r["age"], r["vendor"],
                   r["project"], r["amount"], r["memo"]])
        _zebra(ws, 7, i, money_cols=(6,))
    last = ws.max_row
    _data_bar(ws, 6, first, last, color="FFC000")
    _color_scale(ws, 3, first, last, low_is_bad=False)
    if pos:
        _subtotal(ws, 7, 5, "Total committed", 6,
                  sum(r["amount"] for r in pos))
    _finish(ws, 7)

    # ── Open Bills (AP) — from the Bill Tracker ──
    _write_open_bills(wb, bills, bills_synced)

    # ── Dashboard — colored KPI cards ──
    _build_dashboard(dash, mfd, cp, lien, reten, leases, rp, pos, bills,
                     bills_synced)

    # tab colors so the sheet ribbon reads at a glance
    for name, color in (("Draws MFD", C_NAVY), ("Draws CP", "1F6B4C"),
                        ("Lien Clock", "C00000"), ("Lien Retainage", "548235"),
                        ("Leases (excluded)", "808080"),
                        ("RP Billing Status", "7030A0"), ("Unused POs 30d+", "BF8F00")):
        wb[name].sheet_properties.tabColor = color
    dash.sheet_properties.tabColor = C_NAVY

    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    os.chmod(out, stat.S_IRUSR | stat.S_IWUSR)   # 600 — owner-only


def _build_dashboard(dash, mfd, cp, lien, reten, leases, rp, pos, bills,
                     bills_synced: str) -> None:
    mfd_red = [r for r in mfd if r["verdict"] == "RED"]
    mfd_rev = [r for r in mfd if r["verdict"] in ("REVIEW", "PENDING")]
    cp_red = [r for r in cp if r["verdict"] == "RED"]
    cp_gap = sum((r["earned"] or 0) - (r["invoiced"] or 0) for r in cp_red)
    past = [r for r in lien if r["status"] == "PAST"]
    urgent = [r for r in lien if r["status"] == "URGENT"]
    watch = [r for r in lien if r["status"] == "WATCH"]

    dash.column_dimensions["A"].width = 3
    dash.column_dimensions["B"].width = 40
    dash.column_dimensions["C"].width = 16
    dash.column_dimensions["D"].width = 66

    dash.append(["", "MONEY BLEEDS — company health exceptions"])
    dash.merge_cells("B1:D1")
    t = dash.cell(1, 2)
    t.font = Font(bold=True, size=16, color="FFFFFF")
    t.alignment = Alignment(vertical="center", indent=1)
    for c in range(1, 5):
        dash.cell(1, c).fill = _HDR_FILL
    dash.row_dimensions[1].height = 34
    dash.append(["", f"Generated {dt.datetime.now():%Y-%m-%d %H:%M}  ·  lien clock "
                 f"runs from the invoice month  ·  RP billing from pour evidence "
                 f"in the crew schedules"])
    dash.cell(2, 2).font = Font(italic=True, color="595959")
    dash.merge_cells("B2:D2")

    def card(section: str, section_color: str, label: str, count: int,
             amount, detail: str, bad: bool):
        dash.append(["", label, amount if amount else "", detail])
        r = dash.max_row
        dash.row_dimensions[r].height = 22
        # left accent stripe in col A
        dash.cell(r, 1).fill = PatternFill("solid", fgColor=section_color)
        fill = PatternFill("solid", fgColor="FCE4E4" if bad else "E7F2E7")
        for c in (2, 3, 4):
            dash.cell(r, c).fill = fill
            dash.cell(r, c).border = _BORDER
        dash.cell(r, 2).font = Font(bold=True, size=11,
                                    color="9C0006" if bad else "1F6B4C")
        if amount:
            a = dash.cell(r, 3)
            a.number_format = CUR
            a.font = Font(bold=True, size=11, color="9C0006" if bad else "1F6B4C")
        dash.cell(r, 4).font = Font(color="595959", size=9)

    def header(text: str, color: str):
        dash.append(["", text])
        r = dash.max_row
        dash.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
        c = dash.cell(r, 2)
        c.fill = PatternFill("solid", fgColor=color)
        c.font = Font(bold=True, color="FFFFFF")
        c.alignment = Alignment(indent=1)
        dash.row_dimensions[r].height = 18

    dash.append([])
    header("DRAWS BILLED, NOT INVOICED", "1F6B4C")
    card("d", "305496", f"MFD draws with NO invoice: {len(mfd_red)}", len(mfd_red),
         None, "; ".join(r["project"] for r in mfd_red) or "all clear", bool(mfd_red))
    card("d", "305496", f"MFD needs review / pending: {len(mfd_rev)}", len(mfd_rev),
         None, "; ".join(r["project"] for r in mfd_rev) or "—", bool(mfd_rev))
    card("d", "1F6B4C", f"CP draws under-invoiced: {len(cp_red)}", len(cp_red),
         cp_gap, "; ".join(r["project"] for r in cp_red) or "all clear", bool(cp_red))

    dash.append([])
    header("LIEN CLOCK — DEADLINE TO KEEP LIEN RIGHTS", "C00000")
    card("l", "C00000", f"PAST deadline: {len(past)}", len(past),
         sum(r["balance"] for r in past), "money with no lien backup", bool(past))
    card("l", "ED7D31", f"URGENT (≤{URGENT_DAYS} days): {len(urgent)}", len(urgent),
         sum(r["balance"] for r in urgent), "notice must go out now", bool(urgent))
    card("l", "FFC000", f"WATCH (≤{WATCH_DAYS} days): {len(watch)}", len(watch),
         sum(r["balance"] for r in watch), "", False)
    card("l", "548235", f"Retainage (own track): {len(reten)}", len(reten),
         sum(r["balance"] for r in reten), "completion-based — not the monthly clock",
         False)
    card("l", "808080", f"Lease/note excluded: {len(leases)}", len(leases),
         sum(r["balance"] for r in leases), "not construction income", False)

    dash.append([])
    header("CASH TO CHASE", "7030A0")
    card("c", "7030A0", f"RP poured, not billed: {len(rp['invoice_now'])}",
         len(rp["invoice_now"]), rp["due_total"],
         "concrete is down — invoice it (backlog excluded)", bool(rp["invoice_now"]))
    card("c", "BF8F00", f"Unused POs ≥30 days: {len(pos)}", len(pos),
         sum(r["amount"] for r in pos),
         "open POs, no bill (ready-mix blanket POs may be intentional)", bool(pos))

    # ── Pay the subs (AP) — from the Bill Tracker ──
    paid = [b for b in bills if b["ar"] == "paid"]
    unpaid = [b for b in bills if b["ar"] == "unpaid"]
    noinv = [b for b in bills if b["ar"] == "noinv"]
    paid_due = [b for b in paid if b["lien"] == "due"]
    paid_rest = [b for b in paid if b["lien"] != "due"]
    dash.append([])
    header(f"PAY THE SUBS (AP) — Bill Tracker synced {bills_synced or 'unknown'}",
           "C55A11")
    card("b", "C00000", f"Paid by client + lien coming up: {len(paid_due)}",
         len(paid_due), sum(b["open"] for b in paid_due),
         "money is IN and the sub can lien us — pay NOW", bool(paid_due))
    card("b", "BF8F00", f"Paid by client, not yet lien-due: {len(paid_rest)}",
         len(paid_rest), sum(b["open"] for b in paid_rest),
         "money is IN — clear by this month's lien-15 date", bool(paid_rest))
    card("b", "C00000", f"Client hasn't paid us: {len(unpaid)}", len(unpaid),
         sum(b["open"] for b in unpaid),
         "owe the sub, not collected — chase the GC", bool(unpaid))
    card("b", "7030A0", f"No invoice issued yet: {len(noinv)}", len(noinv),
         sum(b["open"] for b in noinv),
         "sub billed us for work we haven't billed the GC for", bool(noinv))
    dash.sheet_view.showGridLines = False


# ────────────────────────── main ─────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="Money Bleeds — company health exceptions report")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    print("\n  MONEY BLEEDS — draws↔invoices · lien clock · RP wrap-up")
    print("  " + "─" * 60)

    # Hard-fail preflight — mounts must be present, same pattern as Synology.
    problems = []
    if not WIP_EXCEL_PATH.exists():
        problems.append(f"WIP workbook not found: {WIP_EXCEL_PATH} (OneDrive synced?)")
    if not BILL_TRACKER_PATH.exists():
        problems.append(f"Bill Tracker not found: {BILL_TRACKER_PATH} (run sync-ap)")
    if not MFD_ROOT.is_dir():
        problems.append(f"Multi Family volume not mounted: {MFD_ROOT}")
    if not CP_ACTIVE_DIR.is_dir():
        problems.append(f"Common volume not mounted: {CP_ACTIVE_DIR}")
    if problems:
        for p in problems:
            print(f"  ✗ {p}")
        return 2

    # one QBO session + one pull per entity for the whole run (the user
    # 2026-07-24) — invoices/POs are downloaded once and shared by every check
    qc = QboCache(verbose=True)
    print("  QBO project-customer map …")
    proj_map = qc.project_customer_map()

    print("  1a. MFD draws vs invoices …")
    mfd = check_mfd_draws(qc, proj_map)
    print(f"      {len(mfd)} active MFD project(s), "
          f"{sum(1 for r in mfd if r['verdict'] == 'RED')} RED")

    print("  1b. CP draws vs invoices …")
    cp = check_cp_draws(qc, proj_map)
    print(f"      {len(cp)} CP project(s) with draws, "
          f"{sum(1 for r in cp if r['verdict'] == 'RED')} RED")

    print("  2.  Lien clock (work month = invoice month) …")
    lien, reten, leases = check_lien_clock(qc, proj_map)
    past = sum(1 for r in lien if r["status"] == "PAST")
    urgent = sum(1 for r in lien if r["status"] == "URGENT")
    print(f"      {len(lien)} open invoice(s) on the clock — "
          f"{past} PAST, {urgent} URGENT · {len(reten)} retainage (own track) "
          f"· {len(leases)} lease/note excluded")

    print("  3.  RP billing status (poured vs backlog) …")

    def _billed_for(key):
        cust = proj_map.get(key)
        if not cust:
            return None
        return sum(float(i.get("TotalAmt") or 0)
                   for i in qc.invoices_for_customer(cust["id"]))

    rp = rp_billing.build(_billed_for)
    print(f"      INVOICE NOW {len(rp['invoice_now'])} scope(s) = ${rp['due_total']:,.0f}"
          f"  ·  backlog {len(rp['backlog'])} = ${rp['backlog_total']:,.0f}"
          f"  ·  draw-based {len(rp.get('draw_based', []))} = ${rp.get('draw_total', 0):,.0f}")

    print("  4.  Unused POs ≥30 days old …")
    pos = check_unused_pos(qc)
    print(f"      {len(pos)} open PO(s), ${sum(r['amount'] for r in pos):,.0f} committed with no bill")

    print("  5.  Open bills (AP) from the Bill Tracker …")
    bills, bills_synced = read_open_bills(BILL_TRACKER_PATH)
    paid_out = sum(b["open"] for b in bills if b["ar"] == "paid")
    print(f"      {len(bills)} open bill(s), ${sum(b['open'] for b in bills):,.0f} to go out "
          f"(${paid_out:,.0f} already funded by clients) · tracker synced {bills_synced}")

    write_workbook(args.out, mfd, cp, lien, reten, leases, rp, pos,
                   bills, bills_synced)
    print(f"\n  ✓ {args.out}  (chmod 600)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
